# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mommodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('price', models.FloatField(max_length=10, verbose_name='价格')),
                ('num', models.IntegerField(default=0, verbose_name='数量')),
                ('detail', models.TextField(default='', max_length=100, verbose_name='说明')),
                ('piture', models.CharField(default='', max_length=100, verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_id', models.CharField(max_length=20, verbose_name='客户名称')),
                ('custom_address', models.CharField(max_length=100, verbose_name='客户地址')),
                ('mommodity_id', models.IntegerField(default=0, verbose_name='商品编号')),
                ('mommodity_name', models.CharField(default='', max_length=20, verbose_name='商品名称')),
                ('num', models.IntegerField(default=0, verbose_name='数量')),
                ('timestamp', models.DateTimeField(verbose_name='订单时间')),
                ('status', models.CharField(choices=[('New', '新订单'), ('Prepare', '准备'), ('Finish', '完成')], default='New', max_length=20, verbose_name='订单状态')),
                ('mobile', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('msg', models.CharField(default='', max_length=100, verbose_name='留言')),
            ],
        ),
    ]
