# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=50, verbose_name='账号')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=2, verbose_name='性别')),
                ('mobile', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='余额')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('vip', models.PositiveSmallIntegerField(default=0, verbose_name='VIP等级')),
            ],
        ),
        migrations.AlterField(
            model_name='mommodity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='价格'),
        ),
    ]
